export interface SKUMapping {
  oldSku: string;
  newSku: string;
}

export const SKUS: SKUMapping[] = [
  { oldSku: "NCR1KG", newSku: "NT-CR-1000" },
  { oldSku: "NCR400", newSku: "NT-CR-400" },
  { oldSku: "NSM1KG", newSku: "NT-SM-1000" },
  { oldSku: "NSM400", newSku: "NT-SM-400" },
  { oldSku: "CR1KG", newSku: "CL-CR-1000" },
  { oldSku: "CR400", newSku: "CL-CR-400" },
  { oldSku: "CHCR1KG", newSku: "CH-CR-1000" },
  { oldSku: "CHCR400", newSku: "CH-CR-400" },
  { oldSku: "CH1KG", newSku: "CH-SM-1000" },
  { oldSku: "CH400", newSku: "CH-SM-400" },
  { oldSku: "SPB1KG", newSku: "SP-CH-1000" },
  { oldSku: "DCR1KG", newSku: "DC-CR-1000" },
  { oldSku: "HPCHCP1KG", newSku: "DC-CP-1000" },
  { oldSku: "HPCHCR500", newSku: "DC-CR-500" },
  { oldSku: "CNCH200", newSku: "PC-HO-200" },
  { oldSku: "CNBB200", newSku: "PC-BB-200" },
  { oldSku: "BCH40", newSku: "SB-CH-40" },
  { oldSku: "BCF40", newSku: "SB-CF-40" },
  { oldSku: "BCC40", newSku: "SB-CC-40" },
  { oldSku: "MSN1KG", newSku: "SM-ST-1000" },
  { oldSku: "MFN 750", newSku: "" },
  { oldSku: "MND 750", newSku: "" },
  { oldSku: "MCH 750", newSku: "" },
  { oldSku: "MFN400", newSku: "" },
  { oldSku: "MND400", newSku: "" },
  { oldSku: "MCH400", newSku: "" },
  { oldSku: "MCF400", newSku: "" },
  { oldSku: "USOAT1KG", newSku: "SO-US-1000" },
  { oldSku: "CHOATS2.5KG", newSku: "SO-CH-2500" },
  { oldSku: "CHOAT1KG", newSku: "SO-CH-1000" },
  { oldSku: "CHOAT400", newSku: "SO-CH-400" },
  { oldSku: "HOAT400", newSku: "SO-HO-400" },
  { oldSku: "CFOAT1KG", newSku: "SO-CF-1000" },
  { oldSku: "DCOAT1KG", newSku: "SO-DC-1000" },
  { oldSku: "DCOAT400", newSku: "SO-DC-400" },
  { oldSku: "CHCF750", newSku: "CF-CN-750" },
  { oldSku: "PCH1KG", newSku: "SP-DC-1000" },
  { oldSku: "PCH36G", newSku: "SP-DC-36" },
  { oldSku: "PKM1KG", newSku: "SP-KM-1000" },
  { oldSku: "PKM37G", newSku: "SP-KM-37" },
  { oldSku: "PCF1KG", newSku: "SP-CF-1000" },
  { oldSku: "PCF37G", newSku: "SP-CF-37" },
  { oldSku: "PTF1KG", newSku: "SP-TF-1000" },
  { oldSku: "PTF37G", newSku: "SP-TF-37" },
  { oldSku: "ACV500", newSku: "AC-VI-500" },
  { oldSku: "MUESLI DC", newSku: "HM-DC-2000" },
  { oldSku: "NEW OATS", newSku: "SO-CF-2000" },
  { oldSku: "NEW OATS ", newSku: "HO-DC-2000" },
  { oldSku: "15 IN ONE", newSku: "SM-BC-400" },
  { oldSku: "DEIT MUESLI", newSku: "DM-NB-400" },
  { oldSku: "MILLET MUESLI", newSku: "MM-ND-400" },
  { oldSku: "DC MUESLI", newSku: "HM-DC-400" },
  { oldSku: "COLD COFFEE MUESLI", newSku: "HM-CF-400" },
  { oldSku: "NEW MASALA OATS", newSku: "MO-HM-400" },
  { oldSku: "NEW MASALA OATS ", newSku: "MO-KF-400" },
  { oldSku: "NEW MASALA OATS  ", newSku: "MO-IM-400" },
];
